server {
    listen 80;
    listen [::]:80;
    server_name 80;

    return 301 https://$BASE_SERVER_NAME:$PORT;
}

server {
    listen       $PORT ssl;
    listen  [::]:$PORT ssl;
    server_name $BASE_SERVER_NAME;
    # suka
    ssl_certificate public/lolan-shoppingcart.com.crt;
    ssl_certificate_key private/lolan-shoppingcart.com.rsa; 

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /api {
        proxy_pass http://$BASE_SERVER_NAME:$BACKEND_PORT;
    }
}