services:
    frontend:
        build: lolanimus/shopping-cart/local/frontend:latest
        ports: 
          - 8000:5000
    backend:
        build: lolanimus/shopping-cart/local/backend:latest
        ports:
          - 8000:4000
volumes:
  name: shopping-cart-db
