name: Front-End build and test worflow

on:
  push:
    branches:
      - "main"
      - "github_actions_dev"
    paths:
      - "**"
      - "!api/**"

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FRONTEND_P: 8080
      BACKEND_P: 5072
      BASE_SERVER_NAME: localhost
      ENVIRONMENT: Development

    steps:
    - uses: actions/checkout@v4
    - name: Build and Run the Front-End Docker image
      run: docker compose up -d --build frontend

    - name: Install npm
      run: docker exec -i shoppingcart-frontend apk add nodejs npm
      
    - name: Run API tests
      run: docker exec -i shoppingcart-frontend npm run test

    - name: Kill the container
      run: docker compose down