name: Front-End build and test worflow

on:
  push:
    branches:
      - "main"
      - "github_actions_dev"
    paths:
      - "**"
      - "!api/**"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Set Env
      run: export $(cat .env | xargs)

    - uses: actions/checkout@v4
    - name: Build and Run the Front-End Docker image
      run: docker compose up -d --build frontend

    - name: Run API tests
      run: docker exec -i frontend npm run test

    - name: Kill the container
      run: docker kill frontend